### ISSUE TITLE
League of Legends Firewall Settings [Request]

### ISSUE THREAD

**Issue by dennyamarojr** [metablaster/WindowsFirewallRuleset#2]
Hi metablaster,

I'm here to ask you, if you could provide the correct port configuration for league of legends, I'm trying to configure myself for is hard to find the right ones.

**Comment by metablaster** [comment]
Hello dennyamarojr, and thank you for your request!

I'll take a look and upload new rules for LoL game soon.
Right now I'm busy, but consider it to be included in the new release in the next 2-3 days.

You'll can subscribe yourself with "Unwatch" link on this site, to be notified once this issue is closed and rules LoL included.

**Comment by dennyamarojr** [comment]
That's great, glad that you will add :).

Yesterday I discover where I was missing, Riot Games just add new executable call RiotClientServices where use the port that previous I used in the LeagueClient.exe, here's a list to help you :)

LoL - RiotClientServices.exe (HTTPS) - TCP Port 443
LoL - RiotClientUx.exe (HTTPS) - TCP Port 443
LoL - RiotClientServices.exe (Game Chat) - TCP Port 5223
LoL - LeagueClientUx.exe (HTTPS) - TCP Port 443
LoL - LeagueClient.exe (HTTP/HTTPS) - TCP Port 80,443
LoL - LeagueClient.exe (PVP.Net) - TCP Port 2099
LoL - League of Legends.exe (Game Client) - UDP Port 5000-5500
LoL - League of Legends.exe (HTTP/HTTPS) - TCP Port 80,443
LoL - League of Legends.exe (PVP.Net) - TCP Port 2099
LoL - League of Legends.exe (Spectator Mode) - UDP 8088
LoL - League of Legends.exe (Spectator Mode) - TCP 8088

all the rules, was created using in remote address  Internet

C:\Riot Games\League of Legends - Here you will find LeagueClient.exe,LeagueClientUx.exe
C:\Riot Games\League of Legends\Game - Here you will find League of Legends.exe
C:\Riot Games\Riot Client - Here you will find RiotClientServices.exe
C:\Riot Games\Riot Client\UX - Here you will find RiotClientUx.exe

**Comment by metablaster** [comment]
Thank you for details on description of ports, it really helps to know how to name rules and to know their purpose.

I also found official support page regarding LoL game firewall setup here:
https://support-leagueoflegends.riotgames.com/hc/en-us/articles/201752664-Troubleshooting-Connection-Issues

Your setup is very close to this link, however there is also some information on google (likely based on this link too), both of which are not exactly up to date, for example game launcher, PVP.net and client updates were introduced and since then the link doesn't seem to reflect those updates, so I ended up with somewhat different, but for the most part same setup.

For example rules for ports TCP/UDP 8088, are disabled until I figure out how to generate traffic for spectator. (any thoughts?)
`RiotClientUx` is not generating network and game client does not generate on port for PVP.net (only launcher does).

Those rules for which I was not able to generate network traffic are there but not enabled by default, you can search for `TODO` inside `Rules\IPv4\Outbound\Games\LeagueOfLegends.ps1` to see. (rules are subject to change and testing)

Feel free to test them if you want and give feedback if you have time, all updates (until release) are in develop branch, and the commit addressing this issue is: 31ffebd68a71d0f292043e43c05e392665436041

This issue will be closed automatically once either release is made or if you close it yourself.
Thank you for your time and stay safe!

**Comment by metablaster** [comment]
The rules for League of Legends are now included in new release:
[Windows Firewall Ruleset v0.5.0](https://github.com/metablaster/WindowsFirewallRuleset/releases/tag/v0.5.0)

Thank you @dennyamarojr again for taking your time!

**Comment by dennyamarojr** [comment]
Sorry to take too long to reply, I just see the message now. I will test all the rules based on the informations and give you a feedback. Notification just comes now, when you release the ruleset 5.0 :(

**Comment by metablaster** [comment]
No problem, and no need to do anything on your side, but any feedback (such as "it works" or "doesn't work") is welcome of course.

**Comment by dennyamarojr** [comment]
Tested here and it seems everythings works fine, and I test without the rules
LoL - RiotClientUx.exe (HTTPS) - TCP Port 443
LoL - League of Legends.exe (PVP.Net) - TCP Port 2099
LoL - League of Legends.exe (Spectator Mode) - UDP 8088
LoL - League of Legends.exe (Spectator Mode) - TCP 8088

Everythings works fine, it seems that RiotClientUx is just for connect to get the background image of the launcher, otherwise do nothing. I test watch some friends playing and works too, it seems no need do allow spectator mode to league of legends.exe

**Comment by metablaster** [comment]
Thank you for confirming those 3 rules are not needed, I'll remove them next time, probably testing `RiotClientUx.exe` again.
