### ISSUE TITLE
Hardening Windows Firewall - No Connection when Turn On the Computer [Ethernet Connection]

### ISSUE THREAD

**Issue by dennyamarojr** [metablaster/WindowsFirewallRuleset#3]
Hi metablaster,

@metablaster I have an issue when I turn on the computer I got an triangle in the network icon, I tried to configure using the scripts available in the project, but it seems that still have the issue. And to get back the connection, I have to disable and enable the adapter 2,3 times in the Network Connections settings in Windows. 

Here's a picture of the problem. 

![network issue when turn on computer](https://user-images.githubusercontent.com/36896116/90030176-96a40180-dc70-11ea-800e-fd76e844fe1e.jpg)

**Comment by metablaster** [comment]
Hello @dennyamarojr, thank you for reporting this.

From your description this is likely not firewall issue because disabling/enabling adapter (multiple times) resolves the problem.
The question is what caused this...?

I'll need more information to help you out and to isolate the problem, here are steps on how to proceed, please report on each step the result you got.

1. First verify that disabling firewalls (both in GPO and in Control Panel) does not resolve the problem then reboot system to see is yellow triangle is still there.
If disabling both firewalls doesn't resolve the issue after reboot then we isolated firewalls and that's not an issue.

If you need help disabling both firewalls here is document which explains how to do it:
[DisableFirewall](https://github.com/metablaster/WindowsFirewallRuleset/blob/develop/Readme/DisableFirewall.md)

If disabling firewalls resolves the problem after system reboot there is no need to follow the rest of steps, let me know if that's the case.

2. If the yellow triangle is still there after disabling firewalls and system reboot then don't restart adapter to make troubleshooting more accurate, and follow below steps:

**NOTE:** copy/paste each command and press enter to execute

* Press Windows key + X then click on Windows PowerShell [**not** Windows PowerShell (Admin)]
* clear DNS cache by executing below command:
```powershell
ipconfig /flushdns
```
* Perform DNS query (wait 2-3 seconds or until command complete)
```powershell
Resolve-DnsName 8.8.8.8 > $home\Desktop\dns.txt
```
* Perform another DNS query (wait 2-3 seconds or until command complete)
```powershell
Resolve-DnsName microsoft.com >> $home\Desktop\dns.txt
```

* Generate basic network information, (wait 2-3 seconds or until command complete)
```powershell
ipconfig /all > $home\Desktop\ipconfig.txt
Get-NetAdapter | ? HardwareInterface | select * > $home\Desktop\adapter.txt
```

Assuming you didn't run administrative PowerShell, this will create 3 text files on your desktop.
[zip them up](https://support.microsoft.com/en-us/help/4028088/windows-zip-and-unzip-files) and upload zip file to
some sharing site such as http://www.tinyupload.com and share your link for me to see what could be the issue.

1. Open control panel and click on "Network and sharing center"
2. Click on "Troubleshoot problems"
3. depending on your system choose different options to troubleshoot problems.
4. what you are looking for is "Diagnose problems" option

If any kind of problem is discovered by "Diagnose problems" troubleshooter please share what does it say, in addition to giving link to your network information.

 3. Final steps to do while you wait for answer:
* Restart your router, and if that doesn't work you can also try reset it to factory defaults.
resetting to factory defaults is done by pushing a toothpick or something like that into a tinny hole in the router.
This will reset router and WI-FI password and the default one can be found on the sticker somewhere on the router.

* Check your LAN cable, verify it is properly connected and functioning.
* Check your adapter driver is up to date, and make sure you install only official driver for your adapter.

* Type each command into elevated powershell to manually reset network on your computer:

```powershell
ipconfig /flushdns
ipconfig /release
ipconfig /renew
netsh winsock reset
netsh int ip reset
ipconfig /release
ipconfig /renew
```

Restart computer to verify your checks.

**Comment by dennyamarojr** [comment]
@metablaster Find the issue , the problem was a tweak that I applied in the network adapter that was causing the issue. I will activate the firewall now, and restart the computer to see if everything is fine.

**Comment by dennyamarojr** [comment]
Firewall not working @metablaster i will make another test, and give the feedback

**Comment by metablaster** [comment]
OK, I'm unable to reproduce the problem, it works just fine on multiple different computers here.

I understand this only happens to you when GPO firewall is enabled?
I'll need more information about your network setup which you can provide with step 2 in my previous post and then perform step 3 too.

Additional information that may help is:
1. Windows version (run: Winver.exe)
2. Any networking software you may have such as, VPN, DNS etc..
3. Have you modified firewall in any way or is it at project defaults?

Anything else, such what you did prior to this problem may help too.

More input you give more likely we'll solve the problem.
Or at least let me know how to reproduce the problem

**Comment by metablaster** [comment]
@dennyamarojr see here is a short guide for troubleshooting:
https://github.com/metablaster/WindowsFirewallRuleset/blob/develop/Readme/NetworkTroubleshooting.md

Let me know if you find it useful.

**Comment by dennyamarojr** [comment]
Is really useful, I reinstall windows 10 due I'm customizing so I will test the rules and them give you a feedback :) 

Also is a good thing to added security rules to the project, I will look into some websites and them send to you, Lets make this project bigger! :)

**Comment by metablaster** [comment]
> Also is a good thing to added security rules to the project, I will look into some websites and them send to you

Why not, but know that most "security rules" are usually designed for [nftables](https://en.wikipedia.org/wiki/Nftables) and now if I'm not wrong, deprecated [iptables](https://en.wikipedia.org/wiki/Iptables) (linux firewall), which works differently from Windows firewall.

Something that makes sense for linux distros doesn't have to be useful on Windows, but what ever you find I'll be glad to take a look.

**Comment by dennyamarojr** [comment]
Hi @metablaster I got some good configurations, after apply in my computer I could separate a few settings :)

Here's a link for the reg files: http://s000.tinyupload.com/index.php?file_id=28499738797178528346

Here's the link for the websites where I get some Hardening Firewall/Windows 10 process
https://github.com/simeononsecurity/W10-Optimize-and-Harden
https://github.com/AndyFul/Hard_Configurator
https://www.cisecurity.org/cis-benchmarks/
https://www.cyber.gov.au/acsc/view-all-content/publications/hardening-microsoft-windows-10-version-1909-workstations

I use all these guides to a hardening process, the firewall is a little bit more complex due the vulnerabilities that we can find, needs more research but this is a good starting :)

**Comment by metablaster** [comment]
[Uh-Oh](https://www.merriam-webster.com/dictionary/uh-oh) I won't comment on hardening software settings because that's completely unrelated to firewalls and requires some research to verify integrity and validity of random scripts which one can find on internet before using them.

In any case all this software hardening is already built into Windows or available via download from Microsoft and not hard to manage, using registry is just, ah... are you serious?

I understand you have applied firewall settings from zip file which you attached, file called "FirewallHardeningAugust14th.reg"
I also see that you see it contains vulnerabilities, good..

Since that's about firewall, let me tell you what I think about it by examining "Public profile" first to make it short:

> [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile]
> "DisableUnicastResponsesToMulticastBroadcast"=dword:00000001
> "EnableFirewall"=dword:00000001
> "DefaultOutboundAction"=dword:00000000
> "DefaultInboundAction"=dword:00000001
> "AllowLocalPolicyMerge"=dword:00000000
> "AllowLocalIPsecPolicyMerge"=dword:00000000
> "DisableNotifications"=dword:00000001

First of all editing these settings via registry is waste of time because it's already set by scripts from this project, and even if it's not you can set them in firewall GUI.

You said:

> I got some good configurations, after apply in my computer

Of course you did because this reg file made your firewall not hardened but wakened, it is much worse now then what is project default.
Why? because the reg file sets this: `"DefaultOutboundAction"=dword:00000000`
For example this project default is to block all outbound connections ex. to stop user space trojans and spyware. but the reg file in question has opened a hole for malware.

That's one mistake already in the beginning...

Next there is good example of rules that make no sense, add nothing to security and only make troubleshooting harder:
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\FirewallRules]
"1"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=1|Name=1|"
"2"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=2|Name=2|"
"3"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=3|Name=3|"
"4"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=4|Name=4|"
"5"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=5|Name=5|"
"7"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=7|Name=7|"
...
"252"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=252|Name=252|"
"253"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=253|Name=253|"
"254"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=254|Name=254|"
"255"="v2.30|Action=Block|Active=TRUE|Dir=Out|Protocol=255|Name=255|"
```

First of all protocols in range 144-252 are Unassigned and protocol 255 is reserved.
Listing those clearly shows [the guy](https://github.com/Gorstak1979) knows nothing about IP protocols or firewalls.

Secondly, the only protocols which aren't listed are 6 and 17, which are TCP and UDP, most internet traffic goes trough TCP/UDP which contain no rules.

Then there is a long list of blocked programs, I'll name just a few of them:

* ftp.exe
* PING.EXE
* tftp.exe
* curl.exe

Instead of blocking these valid programs completely as if it's malware (some of which people do use today) it's much better to have specific rules for them in case you want to enable traffic.

Here is another example of mistake:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile]
"DisableUnicastResponsesToMulticastBroadcast"=dword:00000001
"AllowLocalPolicyMerge"=dword:00000001
"AllowLocalIPsecPolicyMerge"=dword:00000001
"EnableFirewall"=dword:00000001
"DefaultOutboundAction"=dword:00000000
"DefaultInboundAction"=dword:00000001
"DisableNotifications"=dword:00000001
```

Here the setting `AllowLocalPolicyMerge"=dword:00000001` tells that rules from control panel should be merged into GPO firewall, which opens a whole host of backdoors for malware and defeats the whole purpose of this project firewall.

There is really no need to investigate any further, the amount of bloat and mistakes I've seen in that reg file is too much for my taste.

I'll give you few advices:

* never run scripts and configurations which you didn't investigate first.
* stay away from github repositories of questionable reputation, open source malware is not taboo
* If you want to have good security on your computer then relax, take a read on below link and you'll see it's pretty easy:
https://github.com/metablaster/WindowsFirewallRuleset/blob/develop/Readme/FAQ.md#does-this-firewall-give-me-the-right-protection

Oh, btw. I don't like the [polish guy](https://github.com/AndyFul) either.

I'm closing this issue, since your system may have been shifted in unrecoverable ways.
If you believe it should be reopened make sure to [provide repro steps and minimal information needed](https://github.com/metablaster/WindowsFirewallRuleset/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by metablaster** [comment]
I would like to inform you that the issue with "No Connection when Turn On the Computer" was likely resolved in current release:
[Windows Firewall Ruleset v0.8.0](https://github.com/metablaster/WindowsFirewallRuleset/releases/tag/v0.8.0)

Problem happened with DHCP configured computers, experienced the same issue after setting DHCP.

**Comment by dennyamarojr** [comment]
Thanks, glad to know. Will try this version
