### ISSUE TITLE
Monitoring Firewall Readme

### ISSUE THREAD

**Issue by electro-logic** [metablaster/WindowsFirewallRuleset#9]
Hello,
I would suggest you to add the tool "Firewall Log Viewer for Windows" to the page "Monitoring Firewall" into the Readme folder.
If you contact the developer it's likely they will send you a coupon code for the open source project.
Cheers,

**Comment by metablaster** [comment]
Thank you for suggestion, this seems to be a new store app and I was not aware of it.
I'll try it out and see if it gives anything new that other methods don't, when I get back to scripting.

**Comment by metablaster** [comment]
Hello,
I was considering to try this app however since last the app is no longer free:\
https://apps.microsoft.com/store/detail/firewall-log-viewer-for-windows/9PG2X0R1ZQ9V

Sadly I'm not willing to pay for it to test it's capabilities but anyway I think it's not appropriate to include it into readme since all the programs mentioned there are free of charge.

Thank you for your suggestion.
